on:
    push:
        branches:
          - master
    workflow_dispatch:

# 同じワークフローが進行中の場合、それを取り消す
concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    build-and-deploy:
        timeout-minutes: 5
        permissions:
            contents: read
        if: ${{ vars.DESTINATION_REPOSITORY }}
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '22'

            - run: corepack enable npm

            # https://docs.github.com/ja/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v4
              env:
                cache-name: cache-node-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: ~/.npm
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

            - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - run: npm ci
            - run: npm run build
            - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
              with:
                deploy_key: ${{ secrets.DESTINATION_REPOSITORY_DEPLOY_KEY }}
                external_repository: ${{ vars.DESTINATION_REPOSITORY }}
                publish_dir: ./docs
                force_orphan: true
                full_commit_message: deploy
